name: PR Checks

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  build_and_test:
    uses: egineering-llc/salesforce-oauth/.github/workflows/build_and_test.yaml
    secrets:
      private-key: ${{ secrets.SALESFORCE_OAUTH_PRIVATE_KEY_BASE64 }}
      public-key: ${{ secrets.SALESFORCE_OAUTH_PUBLIC_KEY_BASE64 }}
      rsa-password: ${{ secrets.SALESFORCE_OAUTH_RSA_PASSWORD }}
      client-id: ${{ secrets.SALESFORCE_OAUTH_CLIENT_ID }}
      client-secret: ${{ secrets.SALESFORCE_OAUTH_CLIENT_SECRET }}
      api-base-url: ${{ secrets.SALESFORCE_BASE_URL }}
      jwt-audience: ${{ secrets.SALESFORCE_JWT_AUDIENCE }}
      jwt-subject: ${{ secrets.SALESFORCE_USERNAME }}

